functional:
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Есть возможность сброса фильтров товаров
  - Товар из корзины можно удалить
  - Корзину можно полностью очистить
  - Есть фильтрация по цене
  - Если товаров больше чем отображается на странице, то можно их загрузить/отобразить переходом по кнопке
  - Есть возможность смены языка
